baseURL = 'https://www.parthu.dev'
languageCode = 'en-us'
title = '</parthu.dev>'
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

[params]
  author = "Parthasarathy Bakthavatsalam"
  info = "Sr. Full Stack | Cloud Native | DevOps"
  description = "Parthasarathy's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "/images/avatar.jpg"
  #gravatar = "b.paarthu@gmail.com"

  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2022

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # Social links
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 1
  url = "https://www.linkedin.com/in/parthasarathy-b/"
  target = "_blank"
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 2
  url = "https://github.com/bparthu"
  target = "_blank"
[[params.social]]
  name = "Medium"
  icon = "fa fa-medium fa-2x"
  weight = 3
  url = "https://medium.com/@b.paarthu"
  target = "_blank"
[[params.social]]
  name = "Resume"
  icon = "fa fa-id-badge fa-2x"
  weight = 4
  url = "https://resume.io/r/4mgqgNB0z"
  target = "_blank"