name: publish-blog
on:
  push:
    branches: [ master ]

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Uses Ruby ENV
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Jekyl build
      run: |
        bundle
        jekyll build
        ls
    - name: push to gh-pages branch
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages-test
        FOLDER: _site
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
