name: publish-blog
on:
  push:
    branches: [ master ]

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Uses Ruby ENV
      uses: ruby/setup-ruby@v1
    - name: Jekyl build
      run: |
        bundle
        jekyll build
        ls
